export const OVERALL_PERFORMANCE = "Overall Performance"
export const LEADER_BOARD = "Leaderboard"
export const PERCENTAGE_LABEL = "Percentage";
export const RANK_LABEL = "Rank";
export const NAME_LABEL = "Name";
export const SKILL_LABEL = "Skill";
export const TOTAL_TEST_TIME_LABEL = "Total Test Time";
export const NUMBER_OF_QUESTIONS_LABEL = "No. of Questions";
export const TIME_SPENT_LABEL = "Time Spent";
export const AUTH_ERROR = "AuthToken not found! Please login.";
